package acmcode.basic_algorithm;

/**
 *
 *
 * Created by jiaohongwei on 2016/9/8.
 */

import java.util.Scanner;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * 找到两个字穿串中不相同的那个字符
 */
public class Test7 {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNext()) {
            String s = scanner.next();
            String t = scanner.next();
            System.out.println(findTheDifference(s, t));
        }

    }

    public static char findTheDifference(String s, String t) {
        char[] a = s.toCharArray();
        char[] b = t.toCharArray();
        int a_value = 0;
        int b_value = 0;
        for (char c : a) {
            a_value += c;
        }
        for (char c : b) {
            b_value += c;
        }
        return (char)(b_value-a_value);
    }


}
